// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/leaderboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leaderboard.get').default>>>>
    }
    '/api/lessons': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lessons.get').default>>>>
    }
    '/api/my-courses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/my-courses.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher_202260b4ad80513664e8a42424ac5d44/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+image@1.10.0_db0@0.3.1_ioredis@5.6.0_magicast@0.3.5/node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}