// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/leaderboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leaderboard.get').default>>>>
    }
    '/api/lessons': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/lessons.get').default>>>>
    }
    '/api/my-courses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/my-courses.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}